baseURL: "https://blog.zhengweiliu.com/"
title: ZhengWei Liu's blogs
paginate: 10 # 首頁文章筆數
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
defaultContentLanguage: "zh-tw"
enableGitInfo: true
enableInlineShortcodes: true
enableEmoji: true # allow Emoji
hasCJKLanguage: true

# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: ZhengWei Liu's blogs
  description: ""
  keywords: [Blog, Portfolio, PaperMod]
  author: ZhengWei, Liu
  # author: ["Me", "You"] # multiple authors
  images: ["mountain-cover.png"]
  
  DateFormat: "Dec 31, 2022"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: open
  tocopen: open
  visitCount: true
  


  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "🏠 ZhengWei's Blog"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: ExampleSite
    subtitle: "This is subtitle"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "ZhengWei Liu ( 劉政威 )"
    Content: |
      Hi there 👋. Welcome to my blog.

  socialIcons:
    - name: "linkedin"
      url: "https://www.linkedin.com/in/zheng-wei-liu-1ab77573/"
    - name: "github"
      url: "https://github.com/zhweiliu"
    - name: "other"
      url: "https://leetcode.com/zhweiliu/"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  # cover:
  #   hidden: false # hide everywhere but not in structured data
  #   hiddenInList: false # hide on list pages and home
  #   hiddenInSingle: false # hide on single page

  # editPost:
  #   URL: "https://github.com/<path_to_repo>/content"
  #   Text: "Suggest Changes" # edit text
  #   appendFilePath: false # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: search
      name: 🔍 Search
      url: /search/
      weight: 10
    - identifier: categories
      name: 🏷️ Categories
      url: /categories/
      weight: 20
    - identifier: archives
      name: 📚 Archives
      url: /archives/
      weight: 30
    

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary